### PR TITLE
[PATCH] enhance check-mime-type.pl: also check property-modified files

### PR DESCRIPTION
**Pull request by maddes-b**
[[[
Enhance hook script check-mime-type.pl to also check property-modified files.

* contrib/hook-scripts/check-mime-type.pl:
  - add option to recognize property-modified files for checks
  - make check for svn:eol-style optional
  - enhance texts and comments to reflect changes
  - rename array "files_added" to "files_to_check" to better fit its usage
  - explicitly mark here document with quotes as interpolating
  - fix script name in comments
  - update copyright and license to reflect switch to ASF

Patch by: Matthias Bücher maddes+subversion@maddes.net
Suggested by: Leo Davis [1]

[1] https://mail-archives.apache.org/mod_mbox/subversion-dev/201403.mbox/%3C1576503.m6XB7udPXQ@hurry.speechfxinc.com%3E
]]]

### CODE REVIEW

**Comment by hartmannathan** [comment]
Hello, Please could you discuss this PR on our dev@ mailing list (dev {at} subversion.apache.org) - see https://subversion.apache.org/mailing-lists.html. Attach the patches (either in Git or SVN format) with a .txt extension to your mail. Thanks!

**Comment by hartmannathan** [comment]
See discussion thread and review at https://lists.apache.org/thread.html/red026ebd7412691b03eb95468993c222dea64443a427be75b2509946%40%3Cdev.subversion.apache.org%3E

**Comment by maddes-b** [comment]
Hi there, sorry for the long delay. I read dev list comments and will re-write history of this pull request. Give me next weekend. Kind regards

**Comment by hartmannathan** [comment]
> Hi there, sorry for the long delay. I read dev list comments and will re-write history of this pull request. Give me next weekend. Kind regards

Thanks! No worries.

**Comment by maddes-b** [comment]
Updated the PR with the changes I send to the mailing list on 2020-12-21 16:22 CET.
Had to rewrite history. Change is now commit 0b45e1736c2bfe88c54e5c8580b46a5ed53b4dac.
Updated issue title and top post to reflect the changes.

**Comment by MarsrockEarth** [comment]
您的来信已收到

**Comment by d-sahlberg** [comment]
@maddes-b Thanks for your patch, committed in r1911931. Sorry for the long delay in getting this sorted!

**Pull request closed without merging**
